name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: error-pages
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
        SOURCE_DIR: 'pages'
        AWS_S3_ENDPOINT: error-pages.eu-central-1.linodeobjects.com
